blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/GurjotSinghAulakh/playwright-testing-framework/discussions
    about: Ask questions or start a discussion here.
